# .github/workflows/docker-publish.yml
name: Docker Build and Push

on:
  push:
    branches:
      - develop
      - production

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Set dynamic tag
      - name: Set dynamic tag
        id: tags
        run: |
          if [ "${{ github.ref_name }}" = "develop" ]; then
            echo "TAG=dev" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" = "production" ]; then
            echo "TAG=prod" >> $GITHUB_ENV
          fi

      # Step 4: Build and Push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
